site_name: My Room
theme:
  name: material
  icon:
    logo: fontawesome/solid/hammer
  palette:
    scheme: slate
    primary: teal
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.path
